name: Test
on: 
  push: 
    branches: ["dev"] 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.24.4
        id: go

      - uses: actions/checkout@v1

      - name: Build
        run: |
          go test ./internal/tests -v
